manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: charybdis
      url-base: https://github.com/victorlucachi
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import:
        - app/west.yml
    - name: charybdis-zmk-module
      remote: charybdis
      revision: main
      path: modules/boards/shields/charybdis
  self:
    path: config
